spring.application.name=product-service
server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://localhost:5434/products_db
spring.datasource.username=admin
spring.datasource.password=Imiko12?
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator
management.endpoints.web.exposure.include=health,info
#JWT
application.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970