spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/users_db
spring.datasource.username=admin
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#token
application.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.jwt.access-token-expiry=900000
application.jwt.refresh-token-expiry=604800000

# Email — MailHog for development
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Frontend URL
application.frontend-url=http://localhost:3000