spring.application.name=cart-service
server.port=8083

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cart TTL (7 days in seconds)
cart.ttl=604800

# JWT
application.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.jwt.access-token-expiry=900000
application.jwt.refresh-token-expiry=604800000

# Actuator
management.endpoints.web.exposure.include=health,info

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html




logging.level.org.springframework.security=DEBUG

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true